/* Core Orça V053 - Levantamento em Obra (integrado ao Supabase) */
let levDocs=[],levDoc=null,levRegistros=[],levMateriais=[],levFotos=[],levObras=[],levPavimentos=[],levEstruturas=[],levComponentes=[];
const levSituacoes={instalar:'A instalar',instalado:'Instalado',ajuste:'Necessita ajuste',verificar:'A verificar'};
const levE= v=>esc(String(v??''));
const levEmpresa=()=>currentUserProfile?.empresa_id;
const levData=()=>new Date().toISOString().slice(0,10);
const levOpt=(arr,sel='',name='nome')=>arr.map(x=>`<option value="${levE(x.id)}" ${x.id===sel?'selected':''}>${levE(x[name]||x.codigo||x.id)}</option>`).join('');
function levAviso(e){toast(e?.message||String(e));console.error('Levantamento:',e)}
async function levInit(){
 if(!levEmpresa())return;
 const [l,o]=await Promise.all([sb.from('levantamentos_obra').select('*').eq('empresa_id',levEmpresa()).order('created_at',{ascending:false}),sb.from('obras_eletricas').select('id,nome,cliente_id').order('nome')]);
 if(l.error)return levAviso(l.error);
 levDocs=l.data||[];levObras=o.data||[];
 if(levDoc){levDoc=levDocs.find(x=>x.id===levDoc.id)||null;if(levDoc)await levAbrir(levDoc.id,false)}
 levRender();
}
function levRender(){
 const p=document.getElementById('lev-conteudo');if(!p)return;
 p.innerHTML=`<div class="lev-bar"><button class="btn primary" onclick="levNovo()">+ Novo levantamento</button><button class="btn secondary" onclick="levInit()">Atualizar</button>${levDoc?`<button class="btn secondary" onclick="levAbrir(null)">Todos os levantamentos</button>`:''}</div>`+
 (levDoc?levRenderDetalhe():`<div class="card"><h3>Levantamentos cadastrados</h3><div class="table-wrap"><table><thead><tr><th>Levantamento</th><th>Obra</th><th>Cliente</th><th>Criado em</th><th>Ações</th></tr></thead><tbody>${levDocs.map(d=>`<tr><td><b>${levE(d.nome)}</b></td><td>${levE(levObras.find(o=>o.id===d.obra_id)?.nome||'—')}</td><td>${levE(clientes.find(c=>c.id===d.cliente_id)?.nome||'—')}</td><td>${levE(d.created_at?.slice(0,10))}</td><td><button class="action-btn" onclick="levAbrir('${d.id}')">Abrir</button><button class="action-btn" onclick="levExcluirDoc('${d.id}')">Excluir</button></td></tr>`).join('')||'<tr><td colspan="5">Nenhum levantamento cadastrado.</td></tr>'}</tbody></table></div></div>`);
}
function levRenderDetalhe(){
 const d=levDoc,group=levAgrupar();return `<div class="card"><h3>${levE(d.nome)}</h3><p>Obra: <b>${levE(levObras.find(o=>o.id===d.obra_id)?.nome||'Sem vínculo')}</b> · Cliente: <b>${levE(clientes.find(c=>c.id===d.cliente_id)?.nome||'Sem vínculo')}</b></p><div class="lev-bar"><button class="btn primary" onclick="levEditarRegistro()">+ Registrar ponto</button><button class="btn secondary" onclick="levGerarLista()">Gerar lista no Core Orça</button><button class="btn secondary" onclick="levCSV()">Exportar CSV</button><button class="btn secondary" onclick="levImprimir()">Relatório / PDF</button><button class="btn secondary" onclick="levNovo('${d.id}')">Editar cabeçalho</button></div></div><div class="lev-stats">${Object.keys(levSituacoes).map(s=>`<div class="card"><small>${levSituacoes[s]}</small><h2>${levRegistros.filter(r=>r.situacao===s).length}</h2></div>`).join('')}</div><div class="card"><h3>Registros de campo</h3><div class="table-wrap"><table><thead><tr><th>Pavimento / Ambiente</th><th>Ponto</th><th>Situação</th><th>Descrição</th><th>Fotos</th><th>Ações</th></tr></thead><tbody>${levRegistros.map(r=>`<tr><td>${levE(r.pavimento)}<br><small>${levE(r.ambiente)}</small></td><td>${levE(r.ponto)}</td><td>${levE(levSituacoes[r.situacao])}</td><td>${levE(r.descricao)}</td><td>${levFotos.filter(f=>f.registro_id===r.id).length}</td><td><button class="action-btn" onclick="levEditarRegistro('${r.id}')">Editar</button><button class="action-btn" onclick="levExcluirRegistro('${r.id}')">Excluir</button></td></tr>`).join('')||'<tr><td colspan="6">Nenhum ponto registrado.</td></tr>'}</tbody></table></div></div><div class="card"><h3>Materiais consolidados</h3><p class="muted">Os materiais são vinculados aos cadastros reais da sua empresa. A lista criada no sistema utiliza apenas itens marcados como “A instalar” ou “Necessita ajuste”.</p><div class="table-wrap"><table><thead><tr><th>Código</th><th>Material</th><th>Unidade</th><th>A instalar</th><th>Instalado</th><th>Ajuste</th><th>A verificar</th></tr></thead><tbody>${group.map(x=>`<tr><td>${levE(x.m.codigo)}</td><td>${levE(x.m.nome)}</td><td>${levE(x.m.unidade)}</td>${Object.keys(levSituacoes).map(s=>`<td>${x[s]||0}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="7">Sem materiais.</td></tr>'}</tbody></table></div></div>`;
}
async function levAbrir(id,redraw=true){
 if(!id){levDoc=null;levRegistros=[];levMateriais=[];levFotos=[];levPavimentos=[];levEstruturas=[];levComponentes=[];levRender();return}
 levDoc=levDocs.find(x=>x.id===id);if(!levDoc)return;
 const req=[sb.from('levantamento_registros').select('*').eq('levantamento_id',id).order('created_at'),sb.from('obra_eletrica_pavimentos').select('*').eq('obra_id',levDoc.obra_id||'00000000-0000-0000-0000-000000000000'),sb.from('obra_eletrica_estruturas').select('*').eq('obra_id',levDoc.obra_id||'00000000-0000-0000-0000-000000000000'),sb.from('obra_eletrica_componentes').select('*').eq('obra_id',levDoc.obra_id||'00000000-0000-0000-0000-000000000000')];
 const [a,b,c,d]=await Promise.all(req);if(a.error)return levAviso(a.error);
 levRegistros=a.data||[];levPavimentos=b.data||[];levEstruturas=c.data||[];levComponentes=d.data||[];
 const ids=levRegistros.map(r=>r.id);levMateriais=[];levFotos=[];
 if(ids.length){const [m,f]=await Promise.all([sb.from('levantamento_materiais').select('*').in('registro_id',ids),sb.from('levantamento_fotos').select('*').in('registro_id',ids)]);if(m.error||f.error)return levAviso(m.error||f.error);levMateriais=m.data||[];levFotos=f.data||[]}
 if(redraw)levRender();
}
function levNovo(id){const d=levDocs.find(x=>x.id===id);openModal(d?'Editar levantamento':'Novo levantamento',`<form id="lev-doc-form"><div class="form-grid"><label>Nome do levantamento*<input id="lev-nome" required value="${levE(d?.nome||'')}"></label><label>Obra (Esquema Vertical)<select id="lev-obra"><option value="">Sem obra</option>${levOpt(levObras,d?.obra_id)}</select></label><label>Cliente<select id="lev-cliente"><option value="">Sem cliente</option>${levOpt(clientes,d?.cliente_id)}</select></label><label class="span-2">Observações<textarea id="lev-obs">${levE(d?.observacoes||'')}</textarea></label></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar</button></div></form>`);
 $('lev-obra').onchange=()=>{const o=levObras.find(x=>x.id===$('lev-obra').value);if(o?.cliente_id)$('lev-cliente').value=o.cliente_id};
 $('lev-doc-form').onsubmit=async e=>{e.preventDefault();const payload={empresa_id:levEmpresa(),nome:$('lev-nome').value.trim(),obra_id:$('lev-obra').value||null,cliente_id:$('lev-cliente').value||null,observacoes:$('lev-obs').value.trim()||null,updated_at:new Date().toISOString()};const q=d?await sb.from('levantamentos_obra').update(payload).eq('id',d.id).select().single():await sb.from('levantamentos_obra').insert(payload).select().single();if(q.error)return levAviso(q.error);closeModal();levDoc=q.data;await levInit();await levAbrir(q.data.id);toast('Levantamento salvo.');};}
function levSelectChange(){const p=$('lev-pav-id')?.value||'';if(p){const x=levPavimentos.find(z=>z.id===p);if(x)$('lev-pav-text').value=x.nome}const s=$('lev-estrutura-id')?.value||'';if(s){const x=levEstruturas.find(z=>z.id===s);if(x)$('lev-ambiente').value=x.nome}levAtualizarVinculos()}
function levAtualizarVinculos(){const p=$('lev-pav-id')?.value||'',s=$('lev-estrutura-id')?.value||'';const es=levEstruturas.filter(x=>!p||x.pavimento_id===p);$('lev-estrutura-id').innerHTML='<option value="">Sem vínculo</option>'+levOpt(es,s);const cs=levComponentes.filter(x=>!s||x.estrutura_id===s);$('lev-componente-id').innerHTML='<option value="">Sem vínculo</option>'+cs.map(x=>`<option value="${levE(x.id)}">${levE(x.identificacao||x.tipo||x.id)}</option>`).join('')}
function levEditarRegistro(id){const r=levRegistros.find(x=>x.id===id);openModal(r?'Editar registro de campo':'Novo registro de campo',`<form id="lev-reg-form"><div class="form-grid"><label>Pavimento do esquema<select id="lev-pav-id"><option value="">Sem vínculo</option>${levOpt(levPavimentos,r?.pavimento_id)}</select></label><label>Pavimento (texto)*<input id="lev-pav-text" required value="${levE(r?.pavimento||'')}"></label><label>Estrutura / quadro<select id="lev-estrutura-id"><option value="">Sem vínculo</option>${levOpt(levEstruturas,r?.estrutura_id)}</select></label><label>Componente do esquema<select id="lev-componente-id"><option value="">Sem vínculo</option></select></label><label>Ambiente*<input id="lev-ambiente" required value="${levE(r?.ambiente||'')}"></label><label>Ponto / identificação*<input id="lev-ponto" required value="${levE(r?.ponto||'')}"></label><label>Disciplina<select id="lev-disciplina">${['Elétrica','Hidráulica','Sanitária','PCI','Climatização','Sistemas','Outra'].map(x=>`<option ${x===r?.disciplina?'selected':''}>${x}</option>`).join('')}</select></label><label>Situação<select id="lev-situacao">${Object.keys(levSituacoes).map(s=>`<option value="${s}" ${s===(r?.situacao||'instalar')?'selected':''}>${levSituacoes[s]}</option>`).join('')}</select></label><label>Data<input type="date" id="lev-data" value="${levE(r?.data_registro||levData())}"></label><label>Prazo<input type="date" id="lev-prazo" value="${levE(r?.prazo||'')}"></label><label>Responsável<input id="lev-responsavel" value="${levE(r?.responsavel||'')}"></label><label class="span-2">Descrição*<textarea id="lev-descricao" required>${levE(r?.descricao||'')}</textarea></label></div><h4>Materiais cadastrados</h4><div id="lev-mat-rows"></div><button type="button" class="btn secondary" onclick="levAddMaterial()">+ Vincular material</button><h4>Fotos de campo</h4><div class="lev-bar"><button type="button" class="btn secondary" onclick="document.getElementById('lev-upload').click()">📁 Escolher arquivos</button><button type="button" class="btn secondary" onclick="document.getElementById('lev-camera').click()">📷 Abrir câmera</button></div><input id="lev-upload" type="file" accept="image/jpeg,image/png,image/webp" multiple style="display:none"><input id="lev-camera" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" style="display:none"><small>Escolha fotos existentes ou tire uma foto com a câmera do dispositivo. Até 10 MB por foto. Fotos enviadas ao Supabase ao salvar.</small><div id="lev-prev-fotos" class="lev-preview-grid"></div><div id="lev-fotos-atuais"></div><div class="modal-actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar registro</button></div></form>`);
 $('lev-pav-id').onchange=levSelectChange;$('lev-estrutura-id').onchange=levSelectChange;levAtualizarVinculos();if(r?.componente_id)$('lev-componente-id').value=r.componente_id;
 (r?levMateriais.filter(x=>x.registro_id===r.id):[]).forEach(levAddMaterial);if(r)levRenderFotos(r.id);
 $('lev-upload').onchange=levPrevisualizar; $('lev-camera').onchange=levPrevisualizar; $('lev-reg-form').onsubmit=e=>levSalvarRegistro(e,r);
}
function levAddMaterial(item){const m=item?.material_id?materiais.find(x=>x.id===item.material_id):null;const div=document.createElement('div');div.className='lev-mat-row';div.innerHTML=`<select class="lev-mat-id" required><option value="">Selecione o material cadastrado</option>${materiais.map(x=>`<option value="${levE(x.id)}" ${m?.id===x.id?'selected':''}>${levE(x.codigo||'')} — ${levE(x.nome)}</option>`).join('')}</select><input type="number" class="lev-mat-qtd" min="0.001" step="0.001" value="${Number(item?.quantidade||1)}" required title="Quantidade"><button type="button" class="btn secondary" onclick="this.parentElement.remove()">×</button>`;$('lev-mat-rows').appendChild(div)}
function levPrevisualizar(){
 const area=$('lev-prev-fotos');if(!area)return;area.innerHTML='';
 for(const f of [...$('lev-upload').files,...$('lev-camera').files]){
  const img=document.createElement('img');img.className='lev-prev-img';img.alt=f.name;const url=URL.createObjectURL(f);img.src=url;img.onload=()=>URL.revokeObjectURL(url);area.appendChild(img);
 }
}
async function levRenderFotos(id){const area=$('lev-fotos-atuais');if(!area)return;const fotos=levFotos.filter(f=>f.registro_id===id);area.innerHTML='<p>Fotos salvas:</p>';for(const f of fotos){const q=await sb.storage.from('levantamento-obra').createSignedUrl(f.storage_path,3600);const div=document.createElement('span');div.className='lev-foto';div.innerHTML=`${q.data?.signedUrl?`<a href="${levE(q.data.signedUrl)}" target="_blank" rel="noopener"><img src="${levE(q.data.signedUrl)}" alt="Foto da obra"></a>`:levE(f.nome_arquivo||'Foto')} <button type="button" class="action-btn" onclick="levRemoverFoto('${f.id}','${id}')">Excluir</button>`;area.appendChild(div)}}
async function levRemoverFoto(id,registro){if(!confirm('Excluir esta fotografia?'))return;const f=levFotos.find(x=>x.id===id);if(!f)return;const del=await sb.storage.from('levantamento-obra').remove([f.storage_path]);if(del.error)return levAviso(del.error);const q=await sb.from('levantamento_fotos').delete().eq('id',id);if(q.error)return levAviso(q.error);levFotos=levFotos.filter(x=>x.id!==id);levRenderFotos(registro)}
async function levSalvarRegistro(e,old){e.preventDefault();const btn=e.target.querySelector('button[type=submit],button.btn.primary');if(btn)btn.disabled=true;try{
 const data={empresa_id:levEmpresa(),levantamento_id:levDoc.id,pavimento_id:$('lev-pav-id').value||null,estrutura_id:$('lev-estrutura-id').value||null,componente_id:$('lev-componente-id').value||null,pavimento:$('lev-pav-text').value.trim(),ambiente:$('lev-ambiente').value.trim(),ponto:$('lev-ponto').value.trim(),disciplina:$('lev-disciplina').value,situacao:$('lev-situacao').value,data_registro:$('lev-data').value||null,prazo:$('lev-prazo').value||null,responsavel:$('lev-responsavel').value.trim()||null,descricao:$('lev-descricao').value.trim(),updated_at:new Date().toISOString()};
 const rows=[...document.querySelectorAll('#lev-mat-rows .lev-mat-row')].map(x=>({material_id:x.querySelector('.lev-mat-id').value,quantidade:Number(x.querySelector('.lev-mat-qtd').value)}));if(rows.some(x=>!x.material_id||!(x.quantidade>0)))return toast('Confira os materiais e quantidades.');
 const q=old?await sb.from('levantamento_registros').update(data).eq('id',old.id).select().single():await sb.from('levantamento_registros').insert(data).select().single();if(q.error)return levAviso(q.error);const rid=q.data.id;
 // Regrava somente os itens deste registro. Se falhar, mostra erro para correção.
 const del=await sb.from('levantamento_materiais').delete().eq('registro_id',rid);if(del.error)return levAviso(del.error);
 if(rows.length){const add=await sb.from('levantamento_materiais').insert(rows.map(x=>({...x,empresa_id:levEmpresa(),registro_id:rid})));if(add.error)return levAviso(add.error)}
 for(const file of [...$('lev-upload').files,...$('lev-camera').files]){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10485760){toast('Foto ignorada: tipo inválido ou acima de 10 MB');continue}const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const path=`${levEmpresa()}/${rid}/${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from('levantamento-obra').upload(path,file,{contentType:file.type});if(up.error){levAviso(up.error);continue}const meta=await sb.from('levantamento_fotos').insert({empresa_id:levEmpresa(),registro_id:rid,storage_path:path,nome_arquivo:file.name});if(meta.error)levAviso(meta.error)}
 closeModal();await levAbrir(levDoc.id);toast('Registro salvo.');
 }finally{if(btn)btn.disabled=false}}
async function levExcluirRegistro(id){if(!confirm('Excluir o registro e seus materiais e fotos?'))return;for(const f of levFotos.filter(x=>x.registro_id===id)){const q=await sb.storage.from('levantamento-obra').remove([f.storage_path]);if(q.error)return levAviso(q.error)}const r=await sb.from('levantamento_registros').delete().eq('id',id);if(r.error)return levAviso(r.error);await levAbrir(levDoc.id)}
async function levExcluirDoc(id){if(!confirm('Excluir todo o levantamento, incluindo registros, materiais e fotos?'))return;await levAbrir(id,false);for(const f of levFotos){const q=await sb.storage.from('levantamento-obra').remove([f.storage_path]);if(q.error)return levAviso(q.error)}const r=await sb.from('levantamentos_obra').delete().eq('id',id);if(r.error)return levAviso(r.error);levDoc=null;await levInit()}
function levAgrupar(){const map=new Map();for(const x of levMateriais){const r=levRegistros.find(y=>y.id===x.registro_id),m=materiais.find(y=>y.id===x.material_id);if(!r||!m)continue;let item=map.get(m.id);if(!item){item={m,instalar:0,instalado:0,ajuste:0,verificar:0};map.set(m.id,item)}item[r.situacao]+=Number(x.quantidade)}return [...map.values()].sort((a,b)=>a.m.nome.localeCompare(b.m.nome))}
async function levGerarLista(){if(!levDoc)return;const items=levAgrupar().map(x=>({m:x.m,qtd:x.instalar+x.ajuste})).filter(x=>x.qtd>0);if(!items.length)return toast('Nenhum material a instalar ou ajustar.');if(!confirm(`Criar lista de materiais com ${items.length} itens no Core Orça?`))return;
 const h={nome:`Levantamento — ${levDoc.nome}`,data_lista:levData(),cliente_id:levDoc.cliente_id||null,responsavel_emissao:currentUserProfile?.nome||currentSession?.user?.email||'',tipo_vinculo:'sem_vinculo',observacoes:`Gerada a partir do levantamento em obra: ${levDoc.nome}. Inclui A instalar + Necessita ajuste.`,total:0,topicos:['Levantamento em Obra']};const a=await sb.from('listas_materiais').insert(h).select().single();if(a.error)return levAviso(a.error);const payload=items.map((x,i)=>({lista_id:a.data.id,material_id:x.m.id,codigo:x.m.codigo||null,descricao:x.m.nome,categoria:x.m.categoria||null,unidade:x.m.unidade||'un',quantidade:x.qtd,valor_unitario:0,observacoes:null,ordem:i,topico:'Levantamento em Obra'}));const b=await sb.from('lista_materiais_itens').insert(payload);if(b.error)return levAviso(b.error);await loadListasMateriais();toast('Lista criada no módulo Lista de Materiais.');}
function levBaixar(nome,conteudo,tipo){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([conteudo],{type:tipo}));a.href=url;a.download=nome;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function levCSV(){const rows=[['Pavimento','Ambiente','Ponto','Disciplina','Situação','Descrição','Responsável','Prazo','Material','Código','Quantidade','Unidade']];for(const r of levRegistros){const ms=levMateriais.filter(x=>x.registro_id===r.id);for(const x of ms.length?ms:[null]){const m=materiais.find(z=>z.id===x?.material_id);rows.push([r.pavimento,r.ambiente,r.ponto,r.disciplina,levSituacoes[r.situacao],r.descricao,r.responsavel,r.prazo,m?.nome,m?.codigo,x?.quantidade,m?.unidade])}}levBaixar('levantamento-obra.csv','\ufeff'+rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8')}
// Fotos convertidas em dados locais antes de abrir a impressão: não dependem
// da expiração de URLs assinadas nem de carregamento externo durante o PDF.
async function levFotoDataURL(path){
 const {data,error}=await sb.storage.from('levantamento-obra').download(path);
 if(error)throw error;
 return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(data)});
}
async function levImprimir(){
 if(!levDoc)return;
 const w=window.open('','_blank');if(!w)return toast('Permita janelas pop-up para imprimir.');
 w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Preparando relatório</title></head><body style="font:15px Arial;padding:32px">Preparando relatório e carregando fotografias…</body></html>');w.document.close();
 const fotos={};let falhas=0;
 for(const f of levFotos){try{(fotos[f.registro_id]??=[]).push(await levFotoDataURL(f.storage_path))}catch(err){console.warn('Foto não disponível para relatório',f.id,err);falhas++}}
 const e=typeof empresa==='object'&&empresa?empresa:{};
 const cliente=clientes.find(c=>c.id===levDoc.cliente_id),obra=levObras.find(o=>o.id===levDoc.obra_id);
 const logo=e.logo_url?`<img class="brand-logo" src="${levE(e.logo_url)}">`:'<div class="brand-mark">⚡</div>';
 const resumo=Object.keys(levSituacoes).map(k=>`<div class="stat"><b>${levRegistros.filter(r=>r.situacao===k).length}</b><span>${levE(levSituacoes[k])}</span></div>`).join('');
 const materiais=levAgrupar();
 const tabela=`<table><thead><tr><th>Código</th><th>Material</th><th>Un.</th><th>A instalar</th><th>Instalado</th><th>Ajuste</th></tr></thead><tbody>${materiais.map(x=>`<tr><td>${levE(x.m.codigo)}</td><td>${levE(x.m.nome)}</td><td>${levE(x.m.unidade)}</td><td>${x.instalar||0}</td><td>${x.instalado||0}</td><td>${x.ajuste||0}</td></tr>`).join('')||'<tr><td colspan="6">Nenhum material vinculado</td></tr>'}</tbody></table>`;
 const cards=levRegistros.map((r,i)=>{
  const ms=levMateriais.filter(x=>x.registro_id===r.id);
  return `<section class="registro"><div class="reg-head"><span class="reg-num">${String(i+1).padStart(2,'0')}</span><div><h3>${levE(r.ponto)}</h3><div class="muted">${levE(r.pavimento)} · ${levE(r.ambiente)} · ${levE(r.disciplina)}</div></div><span class="status">${levE(levSituacoes[r.situacao]||r.situacao)}</span></div><div class="reg-meta"><span><b>Data:</b> ${levE(r.data_registro||'—')}</span><span><b>Responsável:</b> ${levE(r.responsavel||'—')}</span><span><b>Prazo:</b> ${levE(r.prazo||'—')}</span></div><p class="desc">${levE(r.descricao)}</p>${ms.length?`<table><thead><tr><th>Código</th><th>Material</th><th>Quantidade</th></tr></thead><tbody>${ms.map(x=>{const m=materiais.find(z=>z.id===x.material_id);return `<tr><td>${levE(m?.codigo||'—')}</td><td>${levE(m?.nome||'Material indisponível')}</td><td>${Number(x.quantidade).toLocaleString('pt-BR')} ${levE(m?.unidade||'')}</td></tr>`}).join('')}</tbody></table>`:''}${(fotos[r.id]||[]).length?`<div class="photo-title">Registro fotográfico</div><div class="photo-grid">${fotos[r.id].map((src,j)=>`<figure><img src="${src}" alt="Foto ${j+1}"><figcaption>Foto ${j+1} · ${levE(r.ponto)}</figcaption></figure>`).join('')}</div>`:''}</section>`
 }).join('');
 const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Levantamento — ${levE(levDoc.nome)}</title><style>
 @page{size:A4;margin:13mm 14mm 15mm}*{box-sizing:border-box}body{font:11px/1.5 Arial,Helvetica,sans-serif;color:#172033;margin:0;background:white}.doc{max-width:190mm;margin:auto}.top{display:flex;justify-content:space-between;gap:22px;align-items:flex-start;border-bottom:2px solid #1f4fd6;padding-bottom:14px}.brand{display:flex;gap:12px;align-items:center}.brand-logo{max-width:145px;max-height:56px;object-fit:contain}.brand-mark{background:#1f4fd6;color:white;border-radius:9px;font-size:23px;padding:9px}.company h1{font-size:16px;margin:0}.company p{margin:2px 0;color:#667085;font-size:9px}.doc-title{text-align:right}.doc-title small{color:#667085;text-transform:uppercase;letter-spacing:1px}.doc-title h2{color:#1f4fd6;font-size:19px;margin:3px 0}.info{margin:16px 0 12px;padding:12px 14px;background:#f7f9fc;border:1px solid #e4e9f2;border-radius:9px;display:grid;grid-template-columns:1fr 1fr;gap:6px}.info span{display:block}.muted{color:#667085}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:12px 0}.stat{border:1px solid #e4e9f2;border-radius:8px;padding:9px;text-align:center}.stat b{display:block;color:#1f4fd6;font-size:19px}.stat span{font-size:9px;color:#667085}.section-title{font-size:10px;text-transform:uppercase;letter-spacing:.7px;color:#475467;font-weight:700;border-bottom:1px solid #e4e9f2;padding-bottom:6px;margin:22px 0 10px}table{width:100%;border-collapse:collapse;margin:10px 0;border:1px solid #e4e9f2}th{background:#f2f5fa;color:#344054;text-transform:uppercase;font-size:8.5px;padding:8px;text-align:left}td{padding:7px 8px;border-top:1px solid #edf0f5;vertical-align:top}.registro{margin:18px 0 24px;break-inside:auto;border-top:1px solid #dce4ef;padding-top:12px}.reg-head{display:flex;align-items:center;gap:10px;break-after:avoid}.reg-num{background:#1f4fd6;color:#fff;border-radius:6px;padding:7px;font-weight:700}.reg-head h3{margin:0;font-size:13px}.status{margin-left:auto;border:1px solid #d0d5dd;border-radius:12px;padding:3px 8px;white-space:nowrap;font-size:9px}.reg-meta{display:flex;gap:18px;margin:10px 0;color:#475467}.desc{white-space:pre-wrap}.photo-title{font-weight:700;color:#475467;margin-top:12px}.photo-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:8px 0}.photo-grid figure{margin:0;border:1px solid #e4e9f2;border-radius:8px;padding:6px;break-inside:avoid}.photo-grid img{display:block;width:100%;height:62mm;object-fit:contain;background:#f7f9fc}.photo-grid figcaption{color:#667085;text-align:center;font-size:8.5px;padding-top:4px}.footer{border-top:1px solid #e4e9f2;margin-top:25px;padding-top:8px;display:flex;justify-content:space-between;color:#98a2b3;font-size:8.5px}.actions{margin:16px 0;padding:12px;background:#f2f5fa;border-radius:8px}.actions button{padding:9px 14px;cursor:pointer}.warning{color:#a13d00}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}.actions{display:none}}
 </style></head><body><div class="doc"><div class="actions"><button onclick="window.print()">Imprimir / Salvar PDF</button> <span>Escolha “Salvar como PDF” no destino da impressão.</span></div><header class="top"><div class="brand">${logo}<div class="company"><h1>${levE(e.nome_fantasia||e.razao_social||'Core Orça')}</h1><p>${levE([e.cnpj?`CNPJ ${e.cnpj}`:'',e.telefone,e.email].filter(Boolean).join(' • '))}</p><p>${levE([e.endereco,e.cidade,e.uf].filter(Boolean).join(' — '))}</p></div></div><div class="doc-title"><small>Relatório técnico</small><h2>Levantamento em Obra</h2></div></header><div class="info"><span><b>Levantamento:</b> ${levE(levDoc.nome)}</span><span><b>Emissão:</b> ${new Date().toLocaleString('pt-BR')}</span><span><b>Obra:</b> ${levE(obra?.nome||'—')}</span><span><b>Cliente:</b> ${levE(cliente?.nome||'—')}</span></div><div class="stats">${resumo}</div><div class="section-title">Materiais consolidados</div>${tabela}<div class="section-title">Registros de campo e fotografias</div>${cards||'<p>Nenhum registro cadastrado.</p>'}${falhas?`<p class="warning">Atenção: ${falhas} foto(s) não puderam ser carregadas. Verifique as permissões do armazenamento e gere novamente.</p>`:''}<footer class="footer"><span>${levE(e.rodape_documentos||'Documento emitido pelo Core Orça')}</span><span>${new Date().toLocaleDateString('pt-BR')}</span></footer></div><script>window.onload=()=>{Promise.all([...document.images].map(i=>i.complete?Promise.resolve():new Promise(r=>{i.onload=r;i.onerror=r}))).then(()=>setTimeout(()=>window.print(),350))};<\/script></body></html>`;
 w.document.open();w.document.write(html);w.document.close();
}
